### ISSUE TITLE
need help 

### ISSUE THREAD

**Issue by ashir321** [pedro-hs/checkbox.sh#10]
https://github.com/ashir321/checkbox.sh/blob/master/checkbox.sh

kindly help me print from Select Option String instead of its position 

--------------------------------------------------
    [x] Apache
    [x] HA Proxy
    [ ] Nginx
    [ ] Message
--------------------------------------------------
  2/4  |  2 selected
Selected:
0 1
Desired:  Apache HA Proxy
and how to save the desired output in a file

**Comment by pedro-hs** [comment]
How to show text instead of index? (in your fork `https://github.com/ashir321/checkbox.sh/blob/master/checkbox.sh` )

- Change from `will_return_index=true` to `will_return_index=false`
- With this change the text is displayed by default in the output, if you want to show index again, you can call the script like this `source checkbox.sh --index`
- If you want to remove the `Selected:` too, delete this line `printf "Selected:\n"` in main function

**Comment by pedro-hs** [comment]
How to save the output in a file?
- There's a lot of ways to do this, I will give you one example

```
# 1) Execute checkbox
source checkbox.sh
# 2) Join the output with ',' and write in a file called output_file.txt.
# Create the file if not exists and overwrite the content if exist
IFS=, ; echo "${checkbox_output[*]}" > output_file.txt
```

**Comment by pedro-hs** [comment]
If your problem was solved give me a feedback

**Comment by ashir321** [comment]
# 2) Join the output with ',' and write the output in a file called output_file.txt. Create the file if not exists and overwrite the content if exist)
IFS=, ; echo "sudo docker exec -t -i mcube-ansible-container  ansible-playbook /opt/ansible/dev/custom/scripts/retry.yml --tags \"${checkbox_output[*]}\"" > khela_hobe.sh
chmod +x khela_hobe.sh

Thanks, Buddy it's working. thanks a lot.

**Comment by pedro-hs** [comment]
You're welcome
If like this software, please, give a star

**Comment by ashir321** [comment]
Hey Pedro.

Could you help me to create a sub-menu .....
LIke under following given options, [  readonly DEFAULT_OPTIONS=("Elasticsearch" "Analytics")  ]
for Elasticsearch sub-menu 
        ---- Elasticsearch Master
        ---- Elasticsearch Salve
        
If I suppose select  Elasticsearch it will automatically select master and slave both
else I select only Master or only Salve
        
Help me 
Thanks in advance 
Ashir

**Comment by pedro-hs** [comment]
Hey Ashir(@ashir321),

Please describe more what you want
I'll try to help you
If you already resolved your problem, let me know
